export const styles = {
    container: {
      maxWidth: '600px',
      margin: '0 auto',
      padding: '20px',
      textAlign: 'center',
    },
    header: {
      marginBottom: '20px',
    },
    gameInfo: {
      display: 'flex',
      justifyContent: 'space-around',
      marginBottom: '20px',
    },
    input: {
      padding: '10px',
      fontSize: '16px',
      width: '200px',
      marginRight: '10px',
    },
    button: {
      padding: '10px 20px',
      fontSize: '16px',
      backgroundColor: '#4CAF50',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
      margin: '5px',
    },
    message: {
      color: '#e74c3c',
      marginTop: '10px',
    },
    wordList: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '10px',
      justifyContent: 'center',
      marginTop: '20px',
    },
    word: {
      backgroundColor: '#f0f0f0',
      padding: '5px 10px',
      borderRadius: '3px',
      color: '#000000', 
    },
    instructions: {
      backgroundColor: '#f8f9fa',
      padding: '15px',
      borderRadius: '8px',
      marginBottom: '20px',
      textAlign: 'left',
    },
    instructionsButton: {
      background: 'none',
      border: 'none',
      color: '#3498db',
      cursor: 'pointer',
      textDecoration: 'underline',
      fontSize: '1rem',
      marginBottom: '10px',
    },
  };