export const styles = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    minHeight: '100vh', 
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  stats: {
    display: 'flex',
    justifyContent: 'space-around',
    fontSize: '1.2rem',
    marginBottom: '20px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)', 
    gap: '10px',
    perspective: '1000px',
    width: '100%',  
    minHeight: '400px',  
  },  
  card: {
    aspectRatio: '1',
    position: 'relative',
    cursor: 'pointer',
    width: '100%',  
    maxWidth: '120px',
    height: '120px',
    margin: '0 auto',
  },  
  cardInner: {
    position: 'relative',
    width: '100%',
    height: '100%',
    transformStyle: 'preserve-3d',
    transition: 'transform 0.6s',
    display: 'flex', 
    justifyContent: 'center', 
    alignItems: 'center', 
  },  
  cardFront: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    background: '#3498db',
    color: 'white',
    fontSize: '2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
  },
  cardBack: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    background: '#2ecc71',
    transform: 'rotateY(180deg)',
    fontSize: '2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
  },
  button: {
    padding: '10px 20px',
    fontSize: '1rem',
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
  },
  victoryMessage: {
    textAlign: 'center',
    fontSize: '1.5rem',
    color: '#27ae60',
    marginTop: '20px',
    fontWeight: 'bold',
  },
};
  