export const styles = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '15px',
    flexWrap: 'wrap',
    gap: '10px',
  },
  stats: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    fontSize: 'clamp(0.9rem, 2.5vw, 1.2rem)',
    marginBottom: '20px',
    flexWrap: 'wrap',
    gap: '15px',
    padding: '10px',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(70px, 1fr))',
    gap: 'clamp(5px, 2vw, 10px)',
    perspective: '1000px',
    width: '100%',
    maxWidth: '600px',
    margin: '0 auto',
  },
  card: {
    aspectRatio: '1',
    position: 'relative',
    cursor: 'pointer',
    width: '100%',
    maxWidth: '120px',
    height: 'auto',
    margin: '0 auto',
  },
  cardInner: {
    position: 'relative',
    width: '100%',
    height: '100%',
    transformStyle: 'preserve-3d',
    transition: 'transform 0.6s',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardFront: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    background: '#3498db',
    color: 'white',
    fontSize: 'clamp(1.5rem, 4vw, 2rem)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
  },
  cardBack: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    background: '#2ecc71',
    transform: 'rotateY(180deg)',
    fontSize: 'clamp(1.5rem, 4vw, 2rem)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
  },
  button: {
    padding: 'clamp(8px, 2vw, 10px) clamp(15px, 3vw, 20px)',
    fontSize: 'clamp(0.9rem, 2.5vw, 1rem)',
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
  },
  victoryMessage: {
    textAlign: 'center',
    fontSize: 'clamp(1.2rem, 3vw, 1.5rem)',
    color: '#27ae60',
    marginTop: '20px',
    fontWeight: 'bold',
    padding: '0 10px',
  },
};

  