export const styles = {
  container: {
    maxWidth: '600px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: '20px',
  },
  gameInfo: {
    display: 'flex',
    gap: '20px',
  },
  timer: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    color: '#333',
  },
  score: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    color: '#333',
  },
  message: {
    textAlign: 'center',
    marginTop: '20px',
    marginBottom: '20px',
    padding: '10px',
    borderRadius: '5px',
    backgroundColor: '#f8f9fa',
    color: '#333',
    fontWeight: 'bold',
  },
  gameBoard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  wordGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '10px',
    marginBottom: '20px',
  },
  wordButton: {
    padding: '15px',
    textAlign: 'center',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '1rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    },
  },
  solvedGroups: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop: '20px',
  },
  solvedGroup: {
    padding: '10px 15px',
    backgroundColor: '#4CAF50',
    color: 'white',
    borderRadius: '5px',
    fontWeight: 'bold',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  gameOver: {
    textAlign: 'center',
    padding: '30px',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  button: {
    padding: '12px 24px',
    fontSize: '1.1rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: 'all 0.2s ease',
    marginTop: '20px',
    '&:hover': {
      backgroundColor: '#45a049',
      transform: 'translateY(-2px)',
    },
  },
  title: {
    fontSize: '2rem',
    color: '#333',
    margin: '0',
  },
  finalScore: {
    fontSize: '1.5rem',
    color: '#333',
    marginTop: '10px',
  },
  categoriesSolved: {
    fontSize: '1.2rem',
    color: '#666',
    marginTop: '10px',
  },
  difficultySelect: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    padding: '20px',
  },
  difficultyButtons: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  difficultyButton: {
    padding: '16px 32px',
    fontSize: '1.2rem',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    backgroundColor: '#2196f3',
    color: 'white',
    fontWeight: 'bold',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#1976d2',
      transform: 'scale(1.05)',
    },
  },
  skipButton: {
    padding: '12px 24px',
    fontSize: '1rem',
    backgroundColor: '#ff9800',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginTop: '20px',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#f57c00',
    },
  },
  loading: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '1.5rem',
    color: '#666',
  },  
  modeSelect: {
    textAlign: 'center',
    marginTop: '2rem',
  },
  modeButtons: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
    marginTop: '1rem',
  },
  modeButton: {
    padding: '1rem 2rem',
    fontSize: '1.2rem',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    backgroundColor: '#4CAF50',
    color: 'white',
    transition: 'transform 0.2s',
    '&:hover': {
      transform: 'scale(1.05)',
    },
  },
  skipButton: {
    padding: '10px 20px',
    margin: '10px',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '16px',
    color: 'white',
    transition: 'transform 0.1s',
    ':hover': {
      transform: 'scale(1.05)',
    },
    ':active': {
      transform: 'scale(0.95)',
    }
  },
  timer: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    color: '#666',
  },
  instructions: {
    marginBottom: '20px',
    padding: '20px',
    backgroundColor: '#f5f5f5',
    borderRadius: '8px',
    maxWidth: '600px',
    margin: '0 auto 20px'
  },
  modeInstructions: {
    marginBottom: '20px',
    textAlign: 'left',
    padding: '10px'
  },
  message: {
    position: 'fixed',
    top: '20px',
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '10px 20px',
    borderRadius: '5px',
    zIndex: 1000,
    animation: 'fadeIn 0.3s ease-in-out'
  },
  revealedAnswers: {
    marginTop: '20px',
    padding: '15px',
    backgroundColor: '#f5f5f5',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
  },
  loadingNewGroups: {
    textAlign: 'center',
    color: '#666',
    marginTop: '10px',
    fontStyle: 'italic'
  },
};